[buildPlans.IosevkaTermSs12]
family = "IosevkaTermSS12"
spacing = "term"
serifs = "sans"
noCvSs = true
exportGlyphNames = true

  [buildPlans.IosevkaTermSs12.variants]
  inherits = "ss12"

    [buildPlans.IosevkaTermSs12.variants.design]
    one = "no-base"
    two = "straight-neck-serifless"
    five = "oblique-flat-serifless"
    nine = "straight-bar"
    capital-g = "toothed-serifless-hooked"
    capital-l = "serifless"
    capital-m = "hanging-serifless"
    a = "double-storey-tailed"
    c = "serifless"
    d = "tailed-serifless"
    e = "rounded"
    f = "flat-hook-serifless"
    g = "double-storey"
    h = "tailed-serifless"
    i = "tailed-serifed"
    j = "flat-hook-serifed"
    k = "cursive-serifless"
    l = "tailed-serifed"
    m = "tailed-top-left-serifed"
    n = "tailed-motion-serifed"
    p = "eared-serifless"
    q = "diagonal-tailed-serifless"
    r = "corner-hooked-top-serifed"
    s = "serifless"
    t = "bent-hook-short-neck"
    u = "tailed-serifless"
    v = "curly-serifless"
    w = "cursive-serifless"
    x = "semi-chancery-curly-serifless"
    y = "straight-turn-serifless"
    z = "curly-serifless"
    ampersand = "closed"
    at = "fourfold"

[buildPlans.IosevkaTermSs12.weights.Regular]
shape = 400
menu = 400
css = 400
