[buildPlans.IosevkaTermSs05]
family = "IosevkaTermSS05"
spacing = "term"
snapshotFamily = 'Iosevka'
snapshotFeature = {"NWID" = 1, "ss05" = 1}
serifs = "sans"
noCvSs = true
exportGlyphNames = true

  [buildPlans.IosevkaTermSs05.variants]
  inherits = "ss05"

    [buildPlans.IosevkaTermSs05.variants.design]
    one = "no-base"
    nine = "straight-bar"
    capital-l = "serifless"
    capital-m = "hanging-serifless"
    a = "double-storey-tailed"
    c = "serifless"
    d = "tailed-serifless"
    e = "rounded"
    f = "flat-hook-serifless"
    g = "double-storey"
    h = "tailed-serifless"
    i = "tailed-serifed"
    j = "serifed"
    k = "cursive-serifless"
    l = "tailed-serifed"
    m = "tailed-top-left-serifed"
    n = "tailed-motion-serifed"
    p = "eared-motion-serifed"
    q = "diagonal-tailed-serifless"
    r = "corner-hooked-top-serifed"
    s = "serifless"
    t = "bent-hook-short-neck2"
    u = "tailed-serifless"
    v = "curly-serifless"
    w = "cursive-serifless"
    x = "semi-chancery-curly-serifless"
    y = "straight-turn-serifless"
    ampersand = "closed"
    at = "fourfold"

[buildPlans.IosevkaTermSs05.weights.Regular]
shape = 400
menu = 400
css = 400
