#!/bin/bash -xeu

root_dir="$(pwd)"
sarasa_dir="sarasa"
sarasa_nerd_dir="sarasa-nerd"
mkdir -p $sarasa_nerd_dir
cd $sarasa_nerd_dir

for item in ../"$sarasa_dir"/*; do
  if [ -f "$item" ]; then
    extension="${item##*.}"
    if [ "$extension" == "ttf" ]; then
      echo "processing " "$item"
      ../font-patcher -q -l -c --careful "$item"
    fi
  fi
done

echo "generating ttc from ttf"
cd "$root_dir"
python otf2otc.py -o $sarasa_nerd_dir/sarasa-term-sc-nerd.ttc $sarasa_nerd_dir/sarasa-term-sc-nerd-*.ttf
cd "$sarasa_nerd_dir"
echo "creating tarball of ttf files"
COPYFILE_DISABLE=1 tar -czvf sarasa-term-sc-nerd.ttf.tar.gz sarasa-term-sc-*.ttf
echo "creating tarball of ttc files"
COPYFILE_DISABLE=1 tar -czvf sarasa-term-sc-nerd.ttc.tar.gz sarasa-term-sc-*.ttc
echo "creating 7zip of ttc files"
7zr a -mx9 sarasa-term-sc-nerd.ttc.7z sarasa-term-sc-*.ttc
echo "creating 7zip of ttf files"
7zr a -mx9 sarasa-term-sc-nerd.ttf.7z sarasa-term-sc-*.ttf
cd "$root_dir"
